backend:
  name: git-gateway
  branch: main

media_folder: "red/img"
public_folder: "/img"

collections:
  - name: "content"
    label: "網頁文字管理"
    files:
      - file: "red/index.html"
        label: "首頁內容"
        name: "home"
        fields:
          - { label: "標題(ID: main-title)", name: "main-title", widget: "string" }
          - { label: "副標題(ID: sub-title)", name: "sub-title", widget: "string" }